version: '3.9'

services:  

  db:
    image: mysql
    container_name: mysql_db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: example

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin
    restart: always
    ports:
      - "8088:80"  # Changed from 8082:80 to 8088:80
    environment:
      PMA_HOST: db
      MYSQL_ROOT_PASSWORD: example
    depends_on:
      - db

  adminer:
    image: adminer
    container_name: adminer
    restart: always
    ports:
      - "8089:8080"  # Changed from 8081:8080 to 8089:8080

  photogram:
    build: ./photogram
    container_name: photogram_app
    restart: always
    ports:
      - "8080:80"  # Changed from 80:80 to 8080:80
    volumes:
      - userdata:/root
      - ./photogram/php-class-project:/var/www/html
    depends_on:
      - db
      - phpmyadmin

volumes:
  userdata:
