version: '3.9'

services:  

  db:
    image: mysql
    container_name: mysql_db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: example

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin
    restart: always
    ports:
      - "8080:80"
    environment:
      PMA_HOST: db
      MYSQL_ROOT_PASSWORD: example
    depends_on:
      - db
  adminer:
    image: adminer
    container_name: adminer
    restart: always
    ports:
      - 8080:8080

  photogram:
    build: ./photogram
    container_name: photogram_app
    restart: always
    ports:
      - "80:80"
    volumes:
      - userdata:/root
      - ./photogram/php-class-project:/var/www/html
    depends_on:
      - db
      - phpmyadmin

volumes:
  userdata:

